services:
  axon-server:
    image: axoniq/axonserver:2024.2.2-jdk-21
    ports:
      - "8024:8024"  # Axon Server UI
      - "8124:8124"  # Axon Server gRPC
    environment:
      AXONSERVER_HOSTNAME: localhost
      AXONSERVER_NAME: axon-server
    volumes:
      - axonserver-data:/axonserver/data
      - axonserver-events:/axonserver/events

volumes:
  axonserver-data:
  axonserver-events:
