# Common configuration shared between all applications
configserver.name=Docker JHipster Registry
configserver.status=Connected to the JHipster Registry running in Docker

jhipster.security.authentication.jwt.base64-secret=OGYzNTEzMGEzOGZlZDUxOTlmMzg2NDlmNDYwNzAwYjUzYWZmZTM4M2IwNDFkMzM5MTNlMzRiNDE0NGFjMWQ4YQ==
eureka.client.service-url.defaultZone=http://admin:${jhipster.registry.password}@localhost:8761/eureka/
