logging:
  level:
    com:
      agentbanking:
        gateway: INFO
spring:
  application:
    name: apiGateway
management:
  endpoint:
    health:
      access: read-only
      probes:
        enabled: true
      show-details: always
  endpoints:
    access:
      default: none
    jmx:
      exposure:
        exclude: '*'
    web:
      base-path: /management
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
springdoc:
  enable-native-support: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true
